### ISSUE TITLE
about Orion(v2) and SSLError

### ISSUE THREAD

**Issue by xizhimen** [solarwinds/orionsdk-python#23] opened 2018-04-16 02:24 UTC
I try to connect orion use python2 but response error message:
## code:
```
import requests
from orionsdk import SwisClient
import orionsdk

npm_server = '192.168.0.100'
username = 'admin'
password = 'password'

verify = False
if not verify:
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)


swis = SwisClient(npm_server, username, password)

print("Query Test:")
results = swis.query("SELECT Uri From Orion.Nodes Where Nodeid=@id",id=1)

uri=results['results'][0]['Uri']
print(uri)
```

## reponse:

```
Query Test:
Traceback (most recent call last):
  File "/Users/guest_mac/python_code/solarwinds/test.py", line 24, in <module>
    results = swis.query("SELECT Uri From Orion.Nodes Where Nodeid=@id",id=1)
  File "/Library/Python/2.7/site-packages/orionsdk/swisclient.py", line 24, in query
    {'query': query, 'parameters': params}).json()
  File "/Library/Python/2.7/site-packages/orionsdk/swisclient.py", line 50, in _req
    headers={'Content-Type': 'application/json'})
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.0.100', port=17778): Max retries exceeded with url: /SolarWinds/InformationService/v3/Json/Query (Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590)'),))

```

where i the problem any how to fix

**Comment by xizhimen** [comment] 2018-04-17 02:59
![image](https://user-images.githubusercontent.com/19748550/38846298-4c306d20-422e-11e8-9bdd-af32b91c43e6.png)
![image](https://user-images.githubusercontent.com/19748550/38846312-5ba2cb54-422e-11e8-8822-b60bca6b2b3c.png)

**Comment by tdanner** [comment] 2018-04-17 03:07
In that screenshot, I think you have a typo. The IP address starts with "1192..." not "192..."

**Comment by danjagnow** [comment] 2019-10-25 19:24
I'm assuming that the typo was the cause of the issue, so I'm closing this issue.  Please feel free to reopen if there is a problem with the library that needs to be addressed.

**Closed by danjagnow** 2019-10-25 19:24 UTC

**Comment by goutham-kumar** [comment] 2021-02-03 04:49
Hi I am facing "Max retries exceeded with url" while running a simple orion query

`swis = SwisClient(server, username, password)`
`aliases = swis.invoke('Metadata.Entity', 'GetAliases', 'SELECT B.Caption FROM Orion.Nodes B')`
 ` print(aliases)`

could someone please help, whats the issue would be

**Comment by danjagnow** [comment] 2021-02-03 13:56
> Hi I am facing "Max retries exceeded with url" while running a simple orion query

@goutham-kumar, see this discussion in [this issue](https://github.com/psf/requests/issues/1198) in the GitHub repository for Python, and especially [this comment](https://github.com/psf/requests/issues/1198#issuecomment-16146041).  The wording of this error message is deceptive since only one attempt is made.  It may also help to see how [SwisClient](https://github.com/solarwinds/orionsdk-python/blob/master/orionsdk/swisclient.py) implements this.  The [invoke](https://github.com/solarwinds/orionsdk-python/blob/6f341d4e84d1a1275f904105d6e04c6e89678475/orionsdk/swisclient.py#L28-L31) method calls [_req](https://github.com/solarwinds/orionsdk-python/blob/6f341d4e84d1a1275f904105d6e04c6e89678475/orionsdk/swisclient.py#L54-L67), which executes the request, checks the status code, and sets the `reason` based on the error message.  Take a close look at what comes back, and you will probably find the true cause of the error.
